### PR TITLE
tasks for Engagement:  newsletter and Open hours

### PR DESCRIPTION
**Pull request by kjgarza**
## Purpose

This is a new product specification. 
To review go to **Files changed** and click **Display the rich Diff**

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Reviewer, please remember to:

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Ensure you give reasons for the changes you are proposing.

### CODE REVIEW

**Review by mfenner — COMMENTED** [review]
As discussed last week, I will not be reviewing these kinds of pull requests until there is an agreement that we want to use them for this purpose. I am not convinced.

**Comment by kjgarza** [comment]
@mfenner I think the important part of this PR is to notice the change in the specification to include the missing part from the last call (in line 28). 
You are right, the process for changing this documents it is indeed another discussion.

**Review by sarala — APPROVED** [review]
Thanks, can you please do a 10 min presentation at the next open hours to encourage people to add this information. I think you can present what we are trying to do as part of the project too. What do you think?

**Comment by kjgarza** [comment]
@sarala sounds good. we can start with that

**Pull request merged**
